### ISSUE TITLE
What do you need help with?

### ISSUE THREAD

**Issue by akcachy** [madeindra/signal-setup-guide#101]
**Server Version :** (Server v5.31)

**Client Version :** (Android 5.12.1)

**Dependencies :** (Twilio / AWS / MinIO / Nginx / Apache / Self-Signed SSL Certificate / Docker / On Premise Redis / On Premise Postgresql / On Premise Minio / Turn / Localstack)

## Describe what are you trying to achieve
Trying to run the server but not able to recieve message.

## Describe the issue that you face

Tell me which guide that you follow & which step that you do or did not do
You Signal-Setup guide for 5.XX

Getting below error and whant to know what ("/v2/directory/reconcile") do 

```
## Logs
WARN  [2021-05-26 06:52:17,430] org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler: error in database crawl: ProcessingException: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
! java.net.ConnectException: Connection refused (Connection refused)
! at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
! at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
! at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
! at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
! at java.base/java.net.Socket.connect(Socket.java:609)
! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
! at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
! at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
! at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:364)
! at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:259)
! ... 20 common frames omitted
```

**Comment by madeindra** [comment]
Related to CDS, but can this is negligible in v3 or v2, whether it is still optional in v4 or v5 we have not know

**Comment by adityaasoleh** [comment]
You need build CDS service (https://github.com/signalapp/ContactDiscoveryService). the AccountDatabaseCrawler function calling CDS api
