### ISSUE TITLE
What do you need help with?

### ISSUE THREAD

**Issue by boykoy96bg** [madeindra/signal-setup-guide#131]
W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
        at android.security.KeyStore.get(KeyStore.java:233)
        at android.security.KeyStore.get(KeyStore.java:222)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
        at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
        at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:146)
        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:81)
        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:50)
        at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.createAndStoreDatabaseSecret(DatabaseSecretProvider.java:83)
        at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreate(DatabaseSecretProvider.java:43)
        at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:26)

**Comment by boykoy96bg** [comment]
![image](https://user-images.githubusercontent.com/43708667/132153307-c1711040-dec0-4c00-b8cf-3eb735700be0.png)
