### ISSUE TITLE
What do you need help with?

### ISSUE THREAD

**Issue by lahirutm** [madeindra/signal-setup-guide#133]
**Server Version :** (Server v6.5)

**Client Version :** (Android vX.XX.XX / iOS vX.XX.XX / Desktop vX.XX.XX)

**Dependencies :** (Twilio / AWS / MinIO / Nginx / Self-Signed SSL Certificate / Docker / On Premise Redis / On Premise Postgresql / On Premise Minio / Turn / Localstack)

I am getting below error. Can i know what is the issue in my config file. And if any solution for this ?

## Logs

java -jar target/TextSecureServer-6.50.1-dirty-SNAPSHOT.jar server config/config-backup.yml 
INFO  [2021-09-17 12:26:06,479] org.eclipse.jetty.util.log: Logging initialized @2038ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2021-09-17 12:26:06,574] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-09-17 12:26:06,575] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-09-17 12:26:06,606] io.micrometer.datadog.DatadogMeterRegistry: An application key must be configured in order for unit information to be sent to Datadog.
INFO  [2021-09-17 12:26:06,607] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for DatadogMeterRegistry every 10s
INFO  [2021-09-17 12:26:09,322] org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager: Received new config version: 1
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at org.whispersystems.textsecuregcm.util.CertificateUtil.getCertificate(CertificateUtil.java:42)
	at org.whispersystems.textsecuregcm.util.CertificateUtil.buildKeyStoreForPem(CertificateUtil.java:21)
	at org.whispersystems.textsecuregcm.http.FaultTolerantHttpClient$Builder.withTrustedServerCertificate(FaultTolerantHttpClient.java:139)
	at org.whispersystems.textsecuregcm.securebackup.SecureBackupClient.<init>(SecureBackupClient.java:49)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:451)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:225)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:759)
Caused by: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:111)
	... 12 more

**Comment by inzkhan** [comment]
What's your signal server version?
Did you add datadog apikey and environment in your config file?

**Comment by adityaasoleh** [comment]
Your cert on config.yml file is wrong 'CertificateException: Could not parse certificate'
