### ISSUE TITLE
/v1/attestation not found exception in contact discovery

### ISSUE THREAD

**Issue by ashwindatye** [madeindra/signal-setup-guide#23]
I'm getting this exception in Android code: What have I not done right? 

2021-01-21 08:40:02.850 6779-6965/org.thoughtcrime.securesms W/ContactSelectionListFra: null
    org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://www.mydomain.com/v1/attestation/c98e00a4e3ff977a56afefe7362a27e4961e4f19e211febfbb19b897e6b80b15}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1601)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1537)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.makeAttestationRequest(RemoteAttestationUtil.java:91)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.getAndVerifyMultiRemoteAttestation(RemoteAttestationUtil.java:59)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:379)
        at org.thoughtcrime.securesms.contacts.sync.ContactDiscoveryV2.getDirectoryResult(ContactDiscoveryV2.java:69)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:223)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:101)
        at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:436)
        at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:422)

**Comment by madeindra** [comment]
@ashwindatye /v1/attestion is CDS API, if your app can still see registered contact with this error, you can ignore it

**Comment by ashwindatye** [comment]
I am not seeing the other contact i registered via a second phone. That contact is there in my local phone contacts as well. 
@madeindra Are you open to a paid consulting assignment to get the setups fully up and running? Server, Android, iOS

**Comment by madeindra** [comment]
@ashwindatye This is the same to the other discussion, please use older version of Android, your server version is way behind the client version.
