### ISSUE TITLE
Not found url=https://www.mydomain.com/v1/storage/manifest/version/0, 

### ISSUE THREAD

**Issue by ashwindatye** [madeindra/signal-setup-guide#24]
**Describe the issue and what do you intend to do**
Android  uild showing this error during startup

the URL in question is url=https://www.mydomain.com/v1/storage/manifest/version/0, 

W/BaseJob: [JOB::2eafe71f-ad01-4232-aa15-7980183c69f9][StorageSyncJob] Encountered a failing exception. (Time Since Submission: 210027 ms, Lifespan: 86400000 ms, Run Attempt: 1/1)
    org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequestResponse(PushServiceSocket.java:1670)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:1613)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:1607)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getStorageManifestIfDifferentVersion(PushServiceSocket.java:855)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getStorageManifestIfDifferentVersion(SignalServiceAccountManager.java:440)
        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:143)
        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:108)

**Comment by madeindra** [comment]
@ashwindatye I've not checked about /v1/storage/manifest/version API, if this is related to versioned profile, then this API is not yet implemented in v3.21.

Which android version did you use?

**Comment by ashwindatye** [comment]
Yes i checked in Server 3.21 and there is only the /storage/auth route and no other routes there

**Comment by madeindra** [comment]
@ashwindatye That means the API is not yet implemented, I'm afraid there's nothing I can do, please use older Android version
