### ISSUE TITLE
Error PIN Creation on Android

### ISSUE THREAD

**Issue by nhathoangntct** [madeindra/signal-setup-guide#28]
**Describe the issue and what do you intend to do**
Hi Made Indra.
First, thanks for your tutorial, this was very helpful and save many time for me.
I am trying to build the Android App. But in the creen Create PIN, I get this log on my terminal. And I checked on the server but the "/v1/token" route was not found. What i was wrong?
Hope you reply for me!
**What step did you follow or did not follow**

**Screenshots or Log**

**Additional context**
W/ConfirmKbsPinRepository: null
    org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://my.domain/v1/token/fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1613)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1549)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getKeyBackupServiceToken(PushServiceSocket.java:788)
        at org.whispersystems.signalservice.api.KeyBackupService.newSession(KeyBackupService.java:101)
        at org.whispersystems.signalservice.api.KeyBackupService.newPinChangeSession(KeyBackupService.java:58)
        at ai.otalk.chat.pin.PinState.setPin(PinState.java:331)
        at ai.otalk.chat.pin.PinState.onPinChangedOrCreated(PinState.java:161)
        at ai.otalk.chat.lock.v2.ConfirmKbsPinRepository.lambda$setPin$0(ConfirmKbsPinRepository.java:28)
        at ai.otalk.chat.lock.v2.-$$Lambda$ConfirmKbsPinRepository$fkV7Hs-ZUbX1SeY_Bb6DgjxaA8s.run(Unknown Source:6)
        at ai.otalk.chat.util.concurrent.SimpleTask.lambda$run$3(SimpleTask.java:52)
        at ai.otalk.chat.util.concurrent.-$$Lambda$SimpleTask$and3B_0proRD6w4afFeP-yRT4jI.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/PinState: onPinCreateFailure()
W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
W/LOTTIE: Animation contains merge paths but they are disabled.
I/RegistrationUtil: Registration is not yet complete.
    java.lang.Throwable
        at ai.otalk.chat.registration.RegistrationUtil.markRegistrationPossiblyComplete(RegistrationUtil.java:31)
        at ai.otalk.chat.lock.v2.ConfirmKbsPinFragment$2.onAnimationEnd(ConfirmKbsPinFragment.java:129)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
        at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:101)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
W/FrameRateTracker: Bad frame! Took 416 ms (24 dropped frames, or 2.40 FPS)
D/OpenGLRenderer: endAllActiveAnimators on 0xe4ff53f0 (RippleDrawable) with handle 0xb8f617d0
V/Cursor: Filling cursor window with start position:0 required position:0
D/PassphraseRequiredActivity: routeApplicationState(), state: 0
D/BaseActivity: [MainActivity] onCreate()
D/BaseActivity: [MainActivity] onStart()
D/LoggingFragment: [ConversationListFragmen] onCreate()

**Comment by nhathoangntct** [comment]
@madeindra Ok, thank you anyway!
