### ISSUE TITLE
All access to this bucket has been disabled in minio

### ISSUE THREAD

**Issue by smith1993pro** [madeindra/signal-setup-guide#33]
when i want to upload profile pic my server error:
`127.0.0.1 - - [14/Feb/2021:08:16:18 +0000] "PUT /v1/profile/name/GaAEJfDXvBbmOVg3ogMVSgS50RXDKRfPBIaFZ%2FF5c8uZTk%2BtuN5MBKy8eC4oazHubt3HPEtK HTTP/1.1" 204 0 "-" "okhttp/3.12.1" 7
ERROR [2021-02-14 08:16:18,537] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 7932a839952c89ef
**! com.amazonaws.services.s3.model.AmazonS3Exception: All access to this bucket has been disabled. (Service: Amazon S3; Status Code: 403; Error Code: AllAccessDisabled;** Request ID: /minio/mybucket/profiles/VpwZQKmGY5jhfRZPXeahtA; S3 Extended Request ID: 9ec25c52-ba8e-44d6-bedc-f79dde48ba81)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1640)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
! at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
! at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
! at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2101)
! at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2087)
! at org.whispersystems.textsecuregcm.controllers.ProfileController.getAvatarUploadForm(ProfileController.java:325)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:566)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:310)
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:264)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at org.eclipse.jetty.server.Server.handle(Server.java:500)
! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
! at java.base/java.lang.Thread.run(Thread.java:834)
`

my bucket policy is:
![Untitled](https://user-images.githubusercontent.com/79010527/107872156-03d16300-6e5d-11eb-9f8a-080e85846eec.png)

my config:
awsAttachments:
accessKey: xxxxxxxxxxxxxxxxx
accessSecret: xxxxxxxxxxxxxxxxxx
bucket: mybucket
region: us-east-1
endpoint: https://minio-server.mydomain.com/minio 

I use Signal Server v3.21 & Signal Android v4.66.1

thanks a lot.

**Comment by smith1993pro** [comment]
I change endpoint to  https://minio-server.mydomain.com
server log:
`127.0.0.1 - - [14/Feb/2021:11:20:44 +0000] "PUT /v1/profile/name/HaYeB%2B3PfllBKiReCSJ2QKjwXOtrKuc%2F4JvxLtHBipvFFnARlLby0OfypykUJ78OuJZyUev7 HTTP/1.1" 204 0 "-" "okhttp/3.12.1" 38
127.0.0.1 - - [14/Feb/2021:11:20:44 +0000] "GET /v1/profile/form/avatar HTTP/1.1" 200 896 "-" "okhttp/3.12.1" 241`

android side error:
`2021-02-14 03:19:17.256 20770-21088/ W/PushServiceSocket: Push service URL: https://mydomain.com
2021-02-14 03:19:17.257 20770-21088/ W/PushServiceSocket: Opening URL: https://mydomain.com/v1/profile/name/HaYeB%2B3PfllBKiReCSJ2QKjwXOtrKuc%2F4JvxLtHBipvFFnARlLby0OfypykUJ78OuJZyUev7
2021-02-14 03:19:17.412 20770-21088/ W/PushServiceSocket: Push service URL: https://mydomain.com
2021-02-14 03:19:17.413 20770-21088/ W/PushServiceSocket: Opening URL: https://mydomain.com/v1/profile/form/avatar
2021-02-14 03:19:19.195 20770-21088/ W/CreateProfileActivity: null
    org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=h2, code=403, message=, url=https:/minio-server.mydomain.com/mybucket/}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:903)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.setProfileAvatar(PushServiceSocket.java:575)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.setProfileAvatar(SignalServiceAccountManager.java:581)
        at CreateProfileActivity$7.doInBackground(CreateProfileActivity.java:375)
        at CreateProfileActivity$7.doInBackground(CreateProfileActivity.java:358)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

Where is my mistake?

**Comment by smith1993pro** [comment]
uploading profile pic work well now...But sending the attachment encounters an error in android side:

`/BaseJob: [JOB::26035970-b6bb-4ee7-8aa9-78db3107ed76][AttachmentUploadJob] Encountered a retryable exception. (Time Since Submission: 18589 ms, Lifespan: 86400000 ms, Run Attempt: 4/Unlimited)
    org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=h2, code=403, message=, url=https://mydomain.com/mybucket/}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:908)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:765)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:362)
        at .jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:104)
        at .jobs.BaseJob.run(BaseJob.java:21)
        at .jobmanager.JobRunner.run(JobRunner.java:82)
        at .jobmanager.JobRunner.run(JobRunner.java:46)`

in server side:
`[14/Feb/2021:11:47:17 -0500] "GET /v2/attachments/form/upload WS" 200 974 "-" "-"`

in android pushServiceSocket.java:
`  private static final String ATTACHMENT_DOWNLOAD_PATH  = "%d";
  private static final String ATTACHMENT_UPLOAD_PATH    = "";`

**Comment by smith1993pro** [comment]
I fixed it.
change pushServiceSocket.java:
`private static final String ATTACHMENT_DOWNLOAD_PATH = "%d"; 
 private static final String ATTACHMENT_UPLOAD_PATH = "";`
 to 
`private static final String ATTACHMENT_DOWNLOAD_PATH ="attachments/%d";
 private static final String ATTACHMENT_UPLOAD_PATH = "";`

and server side AttachmentControllerV2.java:
` String   objectName   = String.valueOf(attachmentId);`
to

' String   objectName   = "attachments/" + String.valueOf(attachmentId);'

also regenerate **accessKey** and **accessSecret**  for minio. now it works well.
thanks
