### ISSUE TITLE
Only can send and receive one way & message "your version of signal has expired" on android app always displays

### ISSUE THREAD

**Issue by yang093** [madeindra/signal-setup-guide#42]
Hi @madeindra 
I'm using Signal Server v3.21 & Signal Android v4.66.1
When I send a message from device A to device B, device B can receive the message successfully but when I send a message from device B to A, device A can't receive the message and the log file is as below:

org.signal.libsignal.metadata.InvalidMetadataMessageException: org.signal.libsignal.metadata.certificate.InvalidCertificateException: Signature failed
        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:124)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:190)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:138)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:159)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:113)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
     Caused by: org.signal.libsignal.metadata.certificate.InvalidCertificateException: Signature failed
        at org.signal.libsignal.metadata.certificate.CertificateValidator.validate(CertificateValidator.java:45)
        at org.signal.libsignal.metadata.certificate.CertificateValidator.validate(CertificateValidator.java:27)

Could you please help me on this issue? Did you see this issue before?

**Comment by madeindra** [comment]
@yang093 There's a section for expired android on https://github.com/madeindra/signal-setup-guide/tree/master/signal-android

Also, when the message can only be sent to one device, check you UnidentifiedSender value in android build.gradle, if everything is correct, it usually take minutes for newly registered device to be able to send message, close the app on both phone and reopen it, it should work.

**Comment by yang093** [comment]
@madeindra thank you so much. I can make it chat 2 ways and resolve the expired label on Android
