### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by Selciuz** [madeindra/signal-setup-guide#43]
Hello, first of all I thank you for your guide it has been very helpful :)
I find a probem while doing DB migration with :

`java -jar service/target/TextSecureServer-3.21.jar messagedb migrate service/config/config.yml`

It returns : 

`ERROR [2021-03-17 16:23:24,392] liquibase.changelog.ChangeSet: Change Set messagedb.xml::1::moxie failed.  Error: ERROR: relation "messages" already exists [Failed SQL: (0) CREATE TABLE public.messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, relay TEXT NOT NULL, timestamp BIGINT NOT NULL, source TEXT NOT NULL, source_device INTEGER NOT NULL, destination TEXT NOT NULL, destination_device INTEGER NOT NULL, message BYTEA NOT NULL, CONSTRAINT MESSAGES_PKEY PRIMARY KEY (id))]
INFO  [2021-03-17 16:23:24,395] liquibase.lockservice.StandardLockService: Successfully released change log lock
liquibase.exception.MigrationFailedException: Migration failed for change set messagedb.xml::1::moxie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "messages" already exists [Failed SQL: (0) CREATE TABLE public.messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, relay TEXT NOT NULL, timestamp BIGINT NOT NULL, source TEXT NOT NULL, source_device INTEGER NOT NULL, destination TEXT NOT NULL, destination_device INTEGER NOT NULL, message BYTEA NOT NULL, CONSTRAINT MESSAGES_PKEY PRIMARY KEY (id))]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
        at liquibase.Liquibase.update(Liquibase.java:202)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at liquibase.Liquibase.update(Liquibase.java:168)
        at org.whispersystems.textsecuregcm.liquibase.DbMigrateCommand.run(DbMigrateCommand.java:60)
        at org.whispersystems.textsecuregcm.liquibase.NameableDbCommand.run(NameableDbCommand.java:42)
        at org.whispersystems.textsecuregcm.liquibase.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:47)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:406)
Caused by: liquibase.exception.DatabaseException: ERROR: relation "messages" already exists [Failed SQL: (0) CREATE TABLE public.messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, relay TEXT NOT NULL, timestamp BIGINT NOT NULL, source TEXT NOT NULL, source_device INTEGER NOT NULL, destination TEXT NOT NULL, destination_device INTEGER NOT NULL, message BYTEA NOT NULL, CONSTRAINT MESSAGES_PKEY PRIMARY KEY (id))]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1276)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1258)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609)
        ... 13 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "messages" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:398)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy39.execute(Unknown Source)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)
        ... 18 more`

Nonetheless I succeeded at launching the signal server but it keeps showing me a warning continuously: 
`WARN  [2021-03-17 16:26:02,190] org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler: error in database crawl:
! java.lang.IllegalArgumentException: argument "content" is null
! at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4413)
! at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3172)
! at org.whispersystems.textsecuregcm.storage.ActiveUserCounter.getFinalTallies(ActiveUserCounter.java:200)
! at org.whispersystems.textsecuregcm.storage.ActiveUserCounter.onCrawlEnd(ActiveUserCounter.java:70)
! at org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler.lambda$processChunk$0(AccountDatabaseCrawler.java:134)
! at java.base/java.lang.Iterable.forEach(Iterable.java:75)
! at org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler.processChunk(AccountDatabaseCrawler.java:134)
! at org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler.doPeriodicWork(AccountDatabaseCrawler.java:110)
! at org.whispersystems.textsecuregcm.storage.AccountDatabaseCrawler.run(AccountDatabaseCrawler.java:91)
! at java.base/java.lang.Thread.run(Thread.java:834)
`

I don't know if i've done something wrong in the previous steps, if you can enlighten me please :)

Edit: The first error was my mistake i forgot to change the db names in config.yml, but i still get connection refused on the second warning

**Comment by madeindra** [comment]
@Selciuz `relation "messages" already exists` means it already exist

the second one is a waring, which is expected when you did not use CDS, please check FAQ section on the server guide to disable it
