### ISSUE TITLE
FetchError: request to https://my-domain/v1/config failed, reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Selciuz** [madeindra/signal-setup-guide#63]
Hello,
I am stuck in signal-desktop, when i try to run it with my own server i get this following error : 
`C:\Users\Work\Desktop\Signal-Desktop\ts\RemoteConfig.js:21 Uncaught (in promise) HTTPError: promiseAjax catch; code: -1
    at makeHTTPError (C:\Users\Work\Desktop\Signal-Desktop\ts\textsecure\WebAPI.js:413:15)
    at C:\Users\Work\Desktop\Signal-Desktop\ts\textsecure\WebAPI.js:389:20
Original stack:
FetchError: request to https://my-domain/v1/config failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\Work\Desktop\Signal-Desktop\node_modules\node-fetch\lib\index.js:1464:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Initial stack:
Error
    at _outerAjax (C:\Users\Work\Desktop\Signal-Desktop\ts\textsecure\WebAPI.js:408:21)
    at _ajax (C:\Users\Work\Desktop\Signal-Desktop\ts\textsecure\WebAPI.js:561:20)
    at Object.getConfig (C:\Users\Work\Desktop\Signal-Desktop\ts\textsecure\WebAPI.js:623:31)
    at Object.refreshRemoteConfig (C:\Users\Work\Desktop\Signal-Desktop\ts\RemoteConfig.js:35:36)
    at invokeFunc (C:\Users\Work\Desktop\Signal-Desktop\node_modules\lodash\lodash.js:10359:23)
    at leadingEdge (C:\Users\Work\Desktop\Signal-Desktop\node_modules\lodash\lodash.js:10369:26)
    at Object.debounced [as maybeRefreshRemoteConfig] (C:\Users\Work\Desktop\Signal-Desktop\node_modules\lodash\lodash.js:10436:20)
    at Object.initRemoteConfig (C:\Users\Work\Desktop\Signal-Desktop\ts\RemoteConfig.js:20:19)
    at C:\Users\Work\Desktop\Signal-Desktop\ts\background.js:546:36`
I've already changed serverUrl & cdnUrl and serverTrustRoot and certificateAuthority with my own things.
Note : I didn't find the web_api.js file on Signal-Desktop to change certificateAuthority in it.

**Comment by madeindra** [comment]
@Selciuz Which server & client version?

**Comment by Selciuz** [comment]
@madeindra Signal-Server 3.21, Signal-desktop latest version i've cloned the repo and tried even other releases but i get the same result.

**Comment by madeindra** [comment]
@Selciuz it won't work, try the older version that matches the server version, find the version that committed on April 2020

**Comment by Selciuz** [comment]
@madeindra I've tried 1.33.4, yarn grunt fails and it gives : 

`Running "getExpireTime" task
Warning: Cannot read property 'branch' of undefined Used --force, continuing.`

I've tried with --force and did the other commands, but it still says network unreachable

**Comment by madeindra** [comment]
@Selciuz Hmm it might a need an update for the yarn commands. What commands did you use?

**Comment by Selciuz** [comment]
@madeindra 
nvm use 12.13.0
npm install --global yarn
yarn install --frozen-lockfile
yarn grunt
yarn icon-gen
yarn build:webpack
yarn test
yarn start
