### ISSUE TITLE
java.lang.NumberFormatException: For input string: "cache" when running Signal Server

### ISSUE THREAD

**Issue by taftazaniadi** [madeindra/signal-setup-guide#74]
**Server Version :** (Server v5.48)
**Ubuntu Version :** (Ubuntu 20.04)
**JDK Version :** (OpenJDK v11.0.11)

## Describe the issue that you face

I've got problem when i execute command : **java -jar service/target/TextSecureServer-5.48.jar server service/config/config.yml**

## Logs

```
INFO  [2021-05-05 06:58:03,370] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-05-05 06:58:03,382] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-05-05 06:58:03,623] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
java.lang.NumberFormatException: For input string: "cache"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.lettuce.core.RedisURI.buildRedisUriFromUri(RedisURI.java:692)
	at io.lettuce.core.RedisURI.create(RedisURI.java:286)
	at io.lettuce.core.RedisURI.create(RedisURI.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.whispersystems.textsecuregcm.redis.FaultTolerantRedisCluster.<init>(FaultTolerantRedisCluster.java:66)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:312)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:187)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:545)
```

## Screenshots

![image](https://user-images.githubusercontent.com/38445835/117107367-aab60300-adab-11eb-9bf6-42b26b6b54ff.png)

**Comment by madeindra** [comment]
Wrong `config.yml` entry, try deleting `/cache` from the entry in config.yml

**Comment by taftazaniadi** [comment]
Alright, i trying to deleteing ```/cache```..

**Comment by taftazaniadi** [comment]
I've got some error when i try to deleteing ```/cache```..

```
io.dropwizard.configuration.ConfigurationValidationException: service/config/config.yml has an error:
  * cacheCluster must not be null

	at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:240)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:88)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:545)
```

**Comment by madeindra** [comment]
`cacheCluster`? which version are you using?

**Comment by taftazaniadi** [comment]
This problem was solved, i wrong set ```config.yml```..
