### ISSUE TITLE
io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster

### ISSUE THREAD

**Issue by taftazaniadi** [madeindra/signal-setup-guide#81]
**Server Version :** (Server v5.71)

## Describe the issue that you face

Please help me to solved this problem, i've got problem ```Unable to establish a connection to Redis Cluster``` when i execute
```
java -jar service/target/TextSecureServer-3.21.jar server service/config/config.yml
```

## Logs

```
INFO  [2021-05-17 04:30:10,263] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-05-17 04:30:10,273] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-05-17 04:30:10,525] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
WARN  [2021-05-17 04:30:14,806] io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh: Cannot retrieve partition view from redis://127.0.0.1, error: java.util.concurrent.CompletionException: io.lettuce.core.RedisCommandExecutionException: ERR This instance has cluster support disabled
io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster
	at io.lettuce.core.cluster.RedisClusterClient.lambda$assertInitialPartitions$32(RedisClusterClient.java:868)
	at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:887)
	at io.lettuce.core.cluster.RedisClusterClient.assertInitialPartitions(RedisClusterClient.java:867)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:390)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:367)
	at org.whispersystems.textsecuregcm.redis.FaultTolerantRedisCluster.<init>(FaultTolerantRedisCluster.java:88)
	at org.whispersystems.textsecuregcm.redis.FaultTolerantRedisCluster.<init>(FaultTolerantRedisCluster.java:65)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:360)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:196)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:600)
Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from [redis://127.0.0.1]

Details:
	[redis://127.0.0.1]: ERR This instance has cluster support disabled

	Suppressed: io.lettuce.core.RedisCommandExecutionException: ERR This instance has cluster support disabled
		at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137)
		at io.lettuce.core.internal.Exceptions.bubble(Exceptions.java:72)
		at io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh.getException(DefaultClusterTopologyRefresh.java:394)
		at io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh.tryFail(DefaultClusterTopologyRefresh.java:163)
		at io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh.lambda$null$8(DefaultClusterTopologyRefresh.java:140)
		at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
		at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:122)
		at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
		at io.lettuce.core.cluster.topology.TimedAsyncCommand.complete(TimedAsyncCommand.java:52)
		at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
		at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:742)
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:677)
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:594)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: io.lettuce.core.RedisCommandExecutionException: ERR This instance has cluster support disabled
		at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137)
		at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110)
		at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
		... 22 more
```

**Comment by madeindra** [comment]
This `ERR This instance has cluster support disabled` your redis have cluster disabled

**Comment by taftazaniadi** [comment]
Yups, i forgot to modify redis cluster to yes..

Thank you..

**Comment by Osamak0** [comment]
@taftazaniadi In which file did you modify redis cluster to yes?
