### ISSUE TITLE
New Server EC2

### ISSUE THREAD

**Issue by JonnyX11** [madeindra/signal-setup-guide#82]
Hey,

What need to do for run the new server on localhost? What about ec2 endpoint ? DynamoDB endpoint ?

john@signal-group:~/Signal-Server$ java -jar service/target/TextSecureServer-5.50.jar server service/config/config.yml

This is my error:

INFO  [2021-05-19 12:31:30,779] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-05-19 12:31:30,782] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-05-19 12:31:30,874] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
WARN  [2021-05-19 12:31:32,245] io.dropwizard.lifecycle.setup.ExecutorServiceBuilder: Parameter 'maximumPoolSize' is conflicting with unbounded work queues
WARN  [2021-05-19 12:31:32,245] io.dropwizard.lifecycle.setup.ExecutorServiceBuilder: Parameter 'maximumPoolSize' is conflicting with unbounded work queues
INFO  [2021-05-19 12:31:32,257] com.amazonaws.internal.DefaultServiceEndpointBuilder: {appconfig, us-east-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'appconfig.us-east-1.amazonaws.com'.
WARN  [2021-05-19 12:31:34,295] org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager: Error retrieving initial dynamic configuration
! java.net.SocketTimeoutException: connect timed out
! at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
! at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
! at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
! at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
! at java.base/java.net.Socket.connect(Socket.java:609)
! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
! at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
! at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
! ... 32 common frames omitted
! Causing: com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
! at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
! at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
! at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)
! at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)
! at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)
! at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)
! at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:165)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.doInvoke(AmazonAppConfigClient.java:2338)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.invoke(AmazonAppConfigClient.java:2305)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.invoke(AmazonAppConfigClient.java:2294)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.executeGetConfiguration(AmazonAppConfigClient.java:976)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.getConfiguration(AmazonAppConfigClient.java:946)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.retrieveDynamicConfiguration(DynamicConfigurationManager.java:94)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.retrieveInitialDynamicConfiguration(DynamicConfigurationManager.java:116)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.start(DynamicConfigurationManager.java:68)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:330)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:185)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:540)

Thanks in advanced!

**Comment by ankingcodes** [comment]
I believe you need to create accounts on ec2 & dynamodb and then add them on config.yml file ?

**Comment by JonnyX11** [comment]
Yes but there is option via docker 

  dynamo_db:
    image: amazon/dynamodb-local:1.15.0
    container_name: dynamo_db
    ports:
      - '8000:8000'

@madeindra 
right?

**Comment by jacob-pro** [comment]
@JonnyX11 you have opened three issues all with the same question, of setting up DynamoDb for Signal v5 on a local server.

https://github.com/madeindra/signal-setup-guide/issues/79
https://github.com/madeindra/signal-setup-guide/issues/80

Btw, the crash you are experiencing above is not actually relating to the DynamoDb, but it is the DynamicConfigurationManager
which I have mentioned here:
https://github.com/madeindra/signal-setup-guide/issues/80#issuecomment-844131054

Respectfully please can you close this as it is a duplicate, and stop adding more issues.
It will only irritate the project maintainers, and confuse any effort to answer the questions.

**Comment by madeindra** [comment]
As I've said, the docker is still an attempt, I can't rush while experimenting on it, I mostly do it during weekend outside of my work hour, please be patient, this repository will be updated whenever I found something new.

This is a long proces and need people contribution too, you can help by trying first and send and update via pull request.
