### ISSUE TITLE
Infinite Error Loop after starting Server v4.xx

### ISSUE THREAD

**Issue by bilisakuratyan** [madeindra/signal-setup-guide#91]
**Server Version :** (Server v4.xx)

**Client Version :** (Android vX.XX.XX / iOS vX.XX.XX / Desktop vX.XX.XX)

**Dependencies :** (Twilio / AWS / MinIO / Nginx / Apache / Self-Signed SSL Certificate / Docker / On Premise Redis / On Premise Postgresql / On Premise Minio / Turn / Localstack)

## Describe what are you trying to achieve

After I succeeded to get the signal working fine, it went into an infinite error loop, possibly due to the Redis cluster & APN. Need help.

## Describe the issue that you face

I have followed the Signal-Server 4.x guide. 
After starting the signal server, I got the server running and then got an infinite error loop, log of which is given below. It seems to be closely related with Redis cluster & APN

## Logs

```
WARN  [2021-05-26 04:07:41,373] org.whispersystems.textsecuregcm.push.ApnFallbackManager: Exception while operating
! redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 12867 127.0.0.1:7002
! at redis.clients.jedis.Protocol.processError(Protocol.java:115)
! at redis.clients.jedis.Protocol.process(Protocol.java:161)
! at redis.clients.jedis.Protocol.read(Protocol.java:215)
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
! at redis.clients.jedis.Connection.getOne(Connection.java:322)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3142)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3135)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:56)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:47)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager$GetOperation.getPending(ApnFallbackManager.java:239)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager.run(ApnFallbackManager.java:125)
! at java.base/java.lang.Thread.run(Thread.java:829)
WARN  [2021-05-26 04:07:42,375] org.whispersystems.textsecuregcm.push.ApnFallbackManager: Exception while operating
! redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 12867 127.0.0.1:7002
! at redis.clients.jedis.Protocol.processError(Protocol.java:115)
! at redis.clients.jedis.Protocol.process(Protocol.java:161)
! at redis.clients.jedis.Protocol.read(Protocol.java:215)
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
! at redis.clients.jedis.Connection.getOne(Connection.java:322)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3142)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3135)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:56)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:47)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager$GetOperation.getPending(ApnFallbackManager.java:239)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager.run(ApnFallbackManager.java:125)
! at java.base/java.lang.Thread.run(Thread.java:829)
WARN  [2021-05-26 04:07:43,380] org.whispersystems.textsecuregcm.push.ApnFallbackManager: Exception while operating
! redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 12867 127.0.0.1:7002
! at redis.clients.jedis.Protocol.processError(Protocol.java:115)
! at redis.clients.jedis.Protocol.process(Protocol.java:161)
! at redis.clients.jedis.Protocol.read(Protocol.java:215)
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
! at redis.clients.jedis.Connection.getOne(Connection.java:322)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3142)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3135)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:56)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:47)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager$GetOperation.getPending(ApnFallbackManager.java:239)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager.run(ApnFallbackManager.java:125)
! at java.base/java.lang.Thread.run(Thread.java:829)
WARN  [2021-05-26 04:07:44,382] org.whispersystems.textsecuregcm.push.ApnFallbackManager: Exception while operating
! redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 12867 127.0.0.1:7002
! at redis.clients.jedis.Protocol.processError(Protocol.java:115)
! at redis.clients.jedis.Protocol.process(Protocol.java:161)
! at redis.clients.jedis.Protocol.read(Protocol.java:215)
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
! at redis.clients.jedis.Connection.getOne(Connection.java:322)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3142)
! at redis.clients.jedis.BinaryJedis.evalsha(BinaryJedis.java:3135)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:56)
! at org.whispersystems.textsecuregcm.redis.LuaScript.execute(LuaScript.java:47)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager$GetOperation.getPending(ApnFallbackManager.java:239)
! at org.whispersystems.textsecuregcm.push.ApnFallbackManager.run(ApnFallbackManager.java:125)
! at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ankingcodes** [comment]
You can ignore this error ! Server is up at `localhost:8081`.

**Comment by madeindra** [comment]
`warn` is a warning, not an error, it is negligible, but you might want to fix it later

**Comment by bilisakuratyan** [comment]
> You can ignore this error ! Server is up at `localhost:8081`.

but there was an infinite warning loop on the screen that I even can't do anything but the program. Do I need to run the java program in the background, how can I do that? And another question is how can I determine whether the server works fine?
Just try to access the localhost:8081？

**Comment by bilisakuratyan** [comment]
> Well you don't need to do anything to the program. To run in the backgroud, use `nohup` version of the command.
> 
> Access `localhost:port` from browser, change port with your port that you wrote on the config, be it 8080 or 8000. There will be 'Not Found` message returned by the server.

okay, thanks for your help.

**Comment by madeindra** [comment]
Please close the issue if the solution solved it
