### ISSUE TITLE
SIGSEGV on Signal-Desktop

### ISSUE THREAD

**Issue by ankingcodes** [madeindra/signal-setup-guide#94]
I'm getting SIGSEGV error on running "yarn start" on Signal-Desktop client. I have followed the guide step by step and have also downloaded Microsoft-Build-Tools. I'm using WSL2, where I got the following error log:
```
yarn run v1.21.1
$ electron .
NODE_ENV development
NODE_CONFIG_DIR /mnt/c/Users/eclipse-workspace/Signal-Desktop/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/.config/Signal-development
config/get: Did not find user config file, cache is now empty object
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
/mnt/c/Users/eclipse-workspace/Signal-Desktop/node_modules/electron/dist/electron exited with signal SIGSEGV
```
I've also tried the guide using CMD & Powershell, where "yarn install" fails with the following error:
```
gyp: binding.gyp not found (cwd: C:\Users\eclipse-workspace\Signal-Desktop\node_modules\@signalapp\signal-client) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\eclipse-workspace\Signal-Desktop\node_modules\@signalapp\signal-client
```

**Comment by madeindra** [comment]
Which version?

**Comment by ankingcodes** [comment]
Cloned the "development" branch.

**Comment by madeindra** [comment]
Did you mean the latest version? I'm sorry but I've not tried it, maybe someone can help about this

**Comment by ankingcodes** [comment]
I'm running Signal Server v4.x, which version of the Signal Desktop/Android client do you think would be compatible ?

**Comment by FradeMime** [comment]
I have a similar problem , signal-desktop v5.x
`NODE_ENV development
NODE_CONFIG_DIR D:\Project\signal\new-Signal\Signal-Desktop\config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: C:\Users\Administrator\AppData\Roaming\Signal-development
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
`
when i want to use the development server, just like 'http://132.33.22.11:8080', the request will report an error:
`ERROR 2022-01-14T02:31:58.890Z Top-level unhandled promise rejection: HTTPError: promiseAjax catch; code: 0
    at makeHTTPError (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:332:12)
    at _promiseAjax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:274:15)
    at async _retryAjax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:314:16)
Original stack:
TypeError: Protocol "http:" not supported. Expected "https:"
    at __node_internal_captureLargerStackTrace (node:internal/errors:463:5)
    at new NodeError (node:internal/errors:370:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at D:\Project\signal\new-Signal\Signal-Desktop\node_modules\node-fetch\lib\index.js:1441:15
    at new Promise (<anonymous>)
    at fetch (D:\Project\signal\new-Signal\Signal-Desktop\node_modules\node-fetch\lib\index.js:1410:9)
    at _promiseAjax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:239:46)
    at _retryAjax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:314:22)
    at D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:320:29
Initial stack:
Error
    at _outerAjax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:328:21)
    at _ajax (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:615:30)
    at Object.requestVerificationSMS (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\WebAPI.js:856:19)
    at AccountManager.requestSMSVerification (D:\Project\signal\new-Signal\Signal-Desktop\ts\textsecure\AccountManager.js:76:28)
    at requestVerification (D:\Project\signal\new-Signal\Signal-Desktop\ts\state\smart\App.js:25:39)
    at D:\Project\signal\new-Signal\Signal-Desktop\ts\components\StandaloneRegistration.js:97:13
    at D:\Project\signal\new-Signal\Signal-Desktop\ts\components\StandaloneRegistration.js:108:9
    at HTMLUnknownElement.callCallback (D:\Project\signal\new-Signal\Signal-Desktop\node_modules\react-dom\cjs\react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (D:\Project\signal\new-Signal\Signal-Desktop\node_modules\react-dom\cjs\react-dom.development.js:199:16)
    at invokeGuardedCallback (D:\Project\signal\new-Signal\Signal-Desktop\node_modules\react-dom\cjs\react-dom.development.js:256:31)`
